import { useRef, useState } from "react";
import { BsArrowLeft } from "react-icons/bs";

function KeywordSearch({ styles, index, setFormData, formData, setIndex }) {
  const space_keywords = [
    "black_hole",
    "dark_matter",
    "galaxy",
    "nebula",
    "supernova",
    "cosmology",
    "astronomy",
    "exoplanets",
    "space_exploration",
    "milky_way",
    "mars_mission",
    "solar_system",
    "light_year",
    "rocket_science",
    "astrobiology",
    "gravitational_waves",
    "quantum_gravity",
    "space_technology",
    "interstellar_travel",
    "alien_life",
    "astro_physics",
    "spacetime_curvature",
    "astroinformatics",
    "planetary_science",
    "stellar_evolution",
    "celestial_body",
    "space_missions",
    "telescope_technology",
    "orbit_mechanics",
    "moon_exploration",
    "satellite_communication",
    "space_mining",
    "cosmic_ray",
    "event_horizon",
    "dark_energy",
    "space_station",
    "extraterrestrial_intelligence",
    "intergalactic",
    "relativity_theory",
    "space_telescope",
    "big_bang",
    "solar_wind",
    "space_radiation",
    "astrophysics",
    "nebula_formation",
    "planet_formation",
    "gravitational_lensing",
    "red_shift",
    "blue_shift",
    "time_dilation",
    "black_hole_merger",
    "chandra_x_ray",
    "hubble_space_telescope",
    "spacex",
    "nasa",
    "international_space_station",
    "james_webb_telescope",
    "mars_rover",
    "planets_in_the_solar_system",
    "star_cluster",
    "solar_eclipse",
    "lunar_eclipse",
    "dark_matter_detection",
    "space_time_continuum",
    "cosmic_background_radiation",
    "big_data_in_astro",
    "astro_chemistry",
    "orbital_mechanics",
    "space_weather",
    "space_communication",
    "orbital_velocity",
    "spacex_mars",
    "asteroid_belt",
    "near_earth_object",
    "comet_tail",
    "planetary_moons",
    "orbital_rendezvous",
    "rocket_propulsion",
    "star_system",
    "tesseract_theory",
    "wormhole",
    "exoplanet_habitability",
    "terraforming",
    "space_agriculture",
    "space_economics",
    "space_tourism",
    "extraterrestrial_life",
    "asteroid_impact",
    "theory_of_everything",
    "time_travel_theory",
    "space_terraforming",
    "hydrogen_fuel_cells",
    "laser_communication",
    "orbital_debris",
    "planetesimal",
    "red_dwarf_star",
    "white_dwarf_star",
    "black_dwarf_star",
    "neutron_star",
    "pulsar",
    "magnetic_field",
    "gravitational_pull",
    "quantum_entanglement",
    "wormhole_travel",
    "multiverse_theory",
    "dimensional_portals",
    "zero_gravity",
    "microgravity",
    "space_elevator",
    "interstellar_communication",
    "astrography",
    "quantum_teleportation",
    "solar_panel_technology",
    "orbital_period",
    "space_suit",
    "gravity_wave_detector",
    "orbital_station",
    "planetary_ring_system",
    "star_explosion",
    "massive_star",
    "planetesimal_disk",
    "astrogeology",
    "planetary_atmosphere",
    "solar_activity",
    "space_laboratory",
    "deep_space_probe",
    "dark_ages_of_the_universe",
    "lunar_mission",
    "interstellar_medium",
    "astronomical_unit",
    "stellar_magnetism",
    "massive_black_holes",
    "sunspot_activity",
    "space_time_fabric",
    "space_propagation",
    "alien_planets",
    "ancient_aliens",
    "cosmic_scale",
    "gravity_assist",
    "zero_point_energy",
    "gravitational_wave_detector",
    "astrophotography",
    "planetary_science_exploration",
    "hyperspace",
    "planetary_mission",
    "transiting_exoplanet",
    "space_mission_planning",
    "volcanism_on_mars",
    "exoplanet_transit",
    "plasma_jet",
    "solar_flares",
    "orbital_radiation",
    "stellar_collapse",
    "active_galactic_nucleus",
    "interstellar_dust",
    "red_giant_star",
    "space_science_research",
    "exoplanet_atmospheres",
    "transneptunian_objects",
    "gravitational_acceleration",
    "planetary_magnetism",
    "cosmic_voids",
    "twin_star_system",
    "early_universe",
    "cosmic_web",
    "astrobiological_chemistry",
    "space_habitat",
    "intergalactic_travel",
    "magnetosphere",
    "space_station_maintenance",
    "space_mission_design",
    "rocket_launch",
    "quantum_computing_in_space",
    "gravitational_technology",
    "moon_mining",
    "earth_like_planet",
    "extraterrestrial_communication",
    "alien_radio_signals",
    "quasar",
    "dark_matter_research",
    "star_map",
    "quantum_tunneling",
    "astronomical_data_analysis",
    "universe_expansion",
    "space_research_institutes",
    "planetary_science_technology",
    "nebula_exploration",
    "space_drones",
    "gravitational_anomaly",
    "solar_energy_in_space",
    "alien_dna",
    "space_xploration",
    "artificial_gravity",
    "singularity",
    "solar_fusion",
    "star_formation",
    "asteroid_mining",
    "space_traffic_management",
    "asteroid_deflection",
    "galactic_nucleus",
    "space_robots",
    "solar_system_dynamics",
    "orbital_radiation_safety",
    "quantum_physics_in_space",
    "astrophysical_simulations",
    "quantum_space_theory",
    "exoplanet_radiation",
    "comet_nucleus",
    "exoplanet_mission",
    "alien_species",
    "interstellar_phenomena",
    "super_earth_exoplanet",
    "supernova_remnants",
    "galactic_centric_orbit",
    "orbital_lag",
    "space_exploration_funding",
    "galactic_evolution",
    "exo_atmosphere",
    "big_data_astro",
    "astro_navigation",
    "satellite_tracking",
    "planetary_biosignatures",
    "multi_dimensional_space",
    "faster_than_light",
    "dark_energy_research",
    "planetary_science_expeditions",
    "celestial_navigation",
    "stellar_navigation",
    "planetary_transit",
    "intergalactic_tourism",
    "astrophysical_plasma",
    "molecular_astrobiology",
    "pulsar_search",
    "orbital_fuel_depot",
    "cosmic_entity",
    "planetary_climate_change",
    "space_data_storage",
    "space_solar_panels",
    "astroinformatics_platform",
    "stellar_radiation",
    "neutron_star_formation",
    "space_vacuum",
    "orbital_insertion",
    "light_curves",
    "cosmic_jet_streams",
    "solar_panel_efficiency",
    "orbital_dynamics",
    "planetary_science_instruments",
    "heliospheric_research",
    "galactic_rotation_curve",
    "nuclear_fusion_in_space",
    "galaxy_merger",
    "dwarf_planet_exploration",
    "space_propagation_effects",
    "planetary_rovers",
    "zero_gravity_research",
    "space_communications_satellite",
    "space_travel_safety",
    "star_formation_theory",
    "cosmic_dust",
    "universe_end_theory",
    "space_pioneering",
    "exoplanet_classification",
    "cosmic_radiation_detection",
    "extraterrestrial_habitability",
    "interstellar_science",
    "solar_sail_technology",
    "suborbital_flight",
    "cosmic_reionization",
    "satellite_microwave",
    "gravitational_wave_astronomy",
    "space_time_warp",
    "orbital_formation",
    "galactic_vortex",
    "terraforming_technology",
    "cosmic_particle_acceleration",
    "dark_matter_cosmology",
    "lunar_base_building",
    "satellite_technology_research",
    "planets_around_other_stars",
    "planetary_impact",
    "space_economy",
    "astronomical_units",
    "orbital_fluctuations",
    "evolution_of_the_universe",
    "gravitational_wave_sensors",
    "pulsar_timing",
    "life_on_venus",
    "extraterrestrial_exploration",
    "cosmic_cosmetics",
    "magnetar_exploration",
    "deep_space_travel",
    "interstellar_warp_drive",
    "cosmic_time_ dilation",
    "planets_in_formation",
    "radiation_shielding_in_space",
    "crater_formation",
    "space_mission_international_collaboration",
    "theoretical_physics_in_space",
    "space_dust_clouds",
    "planets_moons",
    "solar_system_boundary",
    "cosmic_microwave_background",
    "quantum_entanglement_in_space",
    "deep_space_network",
    "satellite_orbit_design",
    "extraterrestrial_geology",
    "new_horizons_mission",
    "planetary_core_dynamics",
    "astro_quarks",
    "hyperspace_navigation",
    "space_politics",
    "hypothetical_planets",
    "space_vacuum_fluctuations",
    "astronomical_observatories",
    "interstellar_exploration_projects",
    "extraterrestrial_resource_utilization",
  ];

  const selected = formData.research_keyword;

  const [keywords, setKeywords] = useState(space_keywords);
  const pressed = useRef(false);

  const handleKeyword = (elem) => {
    if (!pressed.current) {
      pressed.current = true;
      setTimeout(() => {
        pressed.current = false;
      }, 1000);
      setFormData({ ...formData, research_keyword: elem });
      setIndex((prev) => (prev < 3 ? prev + 1 : 3));
    }
  };

  const handleSearch = (e) => {
    const value = e.target.value.toLowerCase();
    const searched = space_keywords.filter((elem) => elem.includes(value));
    if (searched.length > 0) setKeywords(searched);
    else setKeywords([e.target.value.replace(/\s+/g, "")]);
  };

  return (
    <section
      className={styles.keyword}
      style={{ transform: `translateX(-${index * 100}vw)` }}
    >
      <section>
        <header>
          <h2>Pick up a keyword.</h2>
          <p
            style={{
              fontSize: "12px",
              color: "grey",
              padding: "5px",
              paddingLeft: 0,
            }}
          >
            Keywords play a crucial role in your post's popularity.
          </p>
        </header>
        <section className={styles.keyword_box}>
          <input
            type="text"
            placeholder="Eg., Galaxy"
            onChange={(e) => handleSearch(e)}
          ></input>
          <div className={styles.elements}>
            {keywords.map((elem, index) => (
              <p
                key={index}
                onClick={() => handleKeyword(elem)}
                className={`${
                  elem === selected ? styles.selected_keyword : ""
                }`}
              >
                {elem}
              </p>
            ))}
          </div>
          <div className={styles.buttons}>
            <button
              onClick={() => setIndex((prev) => (prev > 0 ? prev - 1 : 0))}
            >
              <BsArrowLeft />
            </button>
          </div>
        </section>
      </section>
    </section>
  );
}

export default KeywordSearch;
